import React from 'react';
import Header from '../../components/Header/Header';
import Footer from '../../components/Footer/Footer';

const ReportPage = (props) => {
  return (
    <div className="ReportPage">
      <Header history={props.history} />
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <Footer history={props.history} />
    </div>
  );
};

export default ReportPage;
