import React, { useEffect } from 'react';
import Header from '../../components/Header/Header';
import Footer from '../../components/Footer/Footer';
import { useSelector, useDispatch } from 'react-redux';
import { history } from '../../store/store';
import { checkLogin } from '../../store/authentication/authentication';

const ReportPage = (props) => {
  const { loggingIn } = useSelector((state) => state.authentication);
  const dispatch = useDispatch();

  useEffect(() => {
    if (loggingIn === undefined) dispatch(checkLogin());
    if (loggingIn === false) {
      history.push('/prelogin');
    }
  }, [dispatch, loggingIn]);

  return (
    <div className="ReportPage" data-testid="ReportPage">
      <Header history={props.history} />
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <div>ReportPage</div>
      <Footer history={props.history} />
    </div>
  );
};

export default ReportPage;
