# Generated by Django 3.1.2 on 2020-11-08 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(max_length=10, null=True)),
                ('sales', models.CharField(max_length=10, null=True)),
                ('operatingProfit', models.CharField(max_length=10, null=True)),
                ('netIncome', models.CharField(max_length=10, null=True)),
                ('operatingMargin', models.CharField(max_length=10, null=True)),
                ('netProfitMargin', models.CharField(max_length=10, null=True)),
                ('PER', models.CharField(max_length=10, null=True)),
                ('PBR', models.CharField(max_length=10, null=True)),
                ('ROE', models.CharField(max_length=10, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
    ]
