# Generated by Django 3.1.2 on 2020-12-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='fin_score',
            field=models.SmallIntegerField(default=50, null=True),
        ),
    ]
