# Generated by Django 3.1.2 on 2020-12-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
